import Header from "../components/__organism/header/Header";
import SideBar from "../components/__organism/sideBar/SideBar";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <section className="w-full min-h-[calc(100vh-126px)] bg-blue-200 flex flex-col items-start justify-center">
          <div className="w-full flex items-start">
            <SideBar />

            <div className="lg:w-1/2">{children}</div>
          </div>
        </section>
      </body>
    </html>
  );
}
