import Header from "../components/__organism/header/Header";
import SideBar from "../components/__organism/sideBar/SideBar";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <section className="w-full min-h-[calc(100vh-126px)] bg-green-200 flex items-start justify-between p-4 md:p-6 ">
          <div className="w-full  flex items-start lg:gap-[1.72%] ">
            <SideBar />
            <div className="w-full lg:w-[58.05%]">{children}</div>
          </div>
        </section>
      </body>
    </html>
  );
}
