export { default as Logo } from './logo/Logo'
export { default as OtpCodeModal } from './otpCodeModal/OtpCodeModal'
export { default as Title } from './title/Title'
export { default as Input } from './input/Input'
export { default as LinkBox } from './linkBoxe/LinkBox'
export { default as ResendOtp } from './resendOtp/ResendOtp'
